service: garden-aid-iot-hub
provider: aws
runtime: nodejs4.3
defaults: # overwrite defaults
    stage: dev
    region: us-east-1
    memory: 128
    timeout: 3
package:
    include:
      - node_modules
      - src
    exclude:
      - test
functions:
    moisture:
        handler: handler.processMoisture
resources:
  Resources:
    MoistureData:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: "Retain"
      Properties:
        TableName: MoistureData
        AttributeDefinitions:
          -
            AttributeName: DeviceId
            AttributeType: S
          -
            AttributeName: Recorded
            AttributeType: S
        KeySchema:
          -
            AttributeName: DeviceId
            KeyType: HASH
          -
            AttributeName: Recorded
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    SensorThing:
      Type: "AWS::IoT::Thing"
      Properties:
        ThingName: "soil-sensor"
        AttributePayload:
           Attributes:
            SensorType: soil

    SensorThingRule:
      Type: "AWS::IoT::TopicRule"
      Properties:
        RuleName: "soil_sensor_store_data"
        TopicRulePayload:
          RuleDisabled: false
          Sql: "SELECT DeviceId, Recorded, Level FROM 'garden/soil/moisture'"
          Actions:
            -
              DynamoDB:
                TableName: { Ref: MoistureData }
                HashKeyField: "DeviceId"
                HashKeyValue: "DeviceId"
                RangeKeyField: "Recorded"
                RangeKeyValue: "Recorded"
                PayloadField: "Level"
                RoleArn: { Fn::GetAtt: [ IotThingRole, Arn ] }

    SensorThingPolicy:
      Type: "AWS::IoT::Policy"
      Properties:
        PolicyName: "garden_aid_iot_sensor_policy"
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Action: ["iot:Connect"]
              Resource: ["*"]
            - Effect: "Allow"
              Action: ["iot:Publish"]
              Resource: ["*"]

    SensorPolicyPrincipalAttachmentCert2:
      Type: "AWS::IoT::PolicyPrincipalAttachment"
      Properties:
        PolicyName: { Ref: SensorThingPolicy }
        Principal: ${iotCertificateArn}

    SensorThingPrincipalAttachmentCert2:
      Type: "AWS::IoT::ThingPrincipalAttachment"
      Properties:
        ThingName: { Ref: SensorThing }
        Principal: ${iotCertificateArn}

    IotThingRole:
       Type: "AWS::IAM::Role"
       Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Principal:
                  Service:
                    - iot.amazonaws.com
                Action:
                  - sts:AssumeRole
