service: iot-hub
provider: aws
runtime: nodejs4.3
defaults: # overwrite defaults
    stage: dev
    region: us-east-1
    memory: 128
    timeout: 3
package:
    include:
      - node_modules
      - src
    exclude:
      - test
functions:
    moisture:
        handler: handler.processMoisture
resources:
  Resources:
    MoistureData:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: "Retain"
      Properties:
        TableName: MoistureData
        AttributeDefinitions:
          -
            AttributeName: DeviceId
            AttributeType: S
          -
            AttributeName: Recorded
            AttributeType: S
        KeySchema:
          -
            AttributeName: DeviceId
            KeyType: HASH
          -
            AttributeName: Recorded
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5

    SensorThing:
      Type: "AWS::IoT::Thing"
      Properties:
        ThingName: "soil-sensor"
        AttributePayload:
           Attributes:
            SensorType: soil

    SensorThingRule:
      Type: "AWS::IoT::TopicRule"
      Properties:
        RuleName: "soil_sensor_store_data"
        TopicRulePayload:
          RuleDisabled: false
          Sql: "SELECT DeviceId, Recorded, Level FROM '$aws/things/soil-sensor/shadow/update'"
          Actions:
            -
              DynamoDB:
                TableName: { Ref: MoistureData }
                HashKeyField: "DeviceId"
                HashKeyValue: "DeviceId"
                RangeKeyField: "Recorded"
                RangeKeyValue: "Recorded"
                PayloadField: "Level"
                RoleArn: { Fn::GetAtt: [ IotThingRole, Arn ] }
    SensorThingPolicy:
      Type: "AWS::IoT::Policy"
      Properties:
        PolicyName: "garden-aid-iot-sensor-policy"
        PolicyDocument:
            Version: 2012-10-17
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "iot:Connect"
                Resource:
                  - "*"
    SensorThingCertificate:
      Type: "AWS::IoT::Certificate"
      Properties:
        CertificateSigningRequest:
        Status: "ACTIVE"

    SensorPolicyPrincipalAttachment:
      Type": "AWS::IoT::PolicyPrincipalAttachment"
      Properties:
        PolicyName: { Ref: SensorThingPolicy }
        Principal: { Fn::GetAtt: [ SensorThingCertificate, Arn ] }

    SensorThingPrincipalAttachment:
      Type: "AWS::IoT::ThingPrincipalAttachment"
      Properties:
        ThingName: { Ref: SensorThing }
        Principal: { Fn::GetAtt: [ SensorThingCertificate, Arn ] }

    IotThingRole:
       Type: "AWS::IAM::Role"
       Properties:
          AssumeRolePolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Principal:
                  Service:
                    - iot.amazonaws.com
                Action:
                  - sts:AssumeRole
