vars:
stages:
  dev:
    vars: null
    regions:
      us-east-1:
        vars:
          iamRoleArnLambda: >-
            arn:aws:iam::222685691406:role/garden-aid-iot-hub-dev-IamRoleLambda-IJ020PJ4VOTN
          serverlessDeploymentBucketName: >-
            garden-aid-iot-hub-dev-serverlessdeploymentbucket-1l72kgxep0pry
          iotCertificateArn: >-
            arn:aws:iot:us-east-1:222685691406:cert/01075a0130f7ad9f2416148bb31cdc99a037235f5b6d40d8fd92204ecdb8b71b
          iotCertificateArn2: >-
            arn:aws:iot:us-east-1:222685691406:cert/4ebbeb7fc1409cda8b61b99a69b37e2dc6933cad62cab460c2b6b1698a855fed
          sensorThingClientResource: >-
            arn:aws:iot:us-east-1:222685691406:client/${iot:ClientId}
          sensorThingSoilTopicResource: >-
            arn:aws:iot:us-east-1:222685691406:topic/garden/soil/moisture
