service: garden-aid-web-bff
provider:
  name: aws
  runtime: nodejs4.3
defaults: # overwrite defaults
    stage: dev
    region: us-east-1
package:
    include:
      - node_modules
      - src
    exclude:
      - test
functions:
    graphQl:
        handler: index.graphql
        memory: 128
        timeout: 3
        events:
            - http:
                path: graphql
                method: post
                cors: true
