vars: null
stages:
    dev:
        vars: null
        regions:
            ap-southeast-2:
                vars: null
    prod:
        vars: null
        regions:
            ap-southeast-2:
                vars: null
