vars: null
stages:
    dev:
        vars: null
        regions:
            us-east-1:
                vars:
                    iamRoleArnLambda: >-
                        arn:aws:iam::222685691406:role/web-bff-dev-IamRoleLambda-4HNL1XP65DK8
                    serverlessDeploymentBucketName: web-bff-dev-serverlessdeploymentbucket-td99gn6afiw7
    prod:
        vars: null
        regions:
            us-east-1:
                vars: null
